import type { Metadata } from "next";
import { Grandstander } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const grandstander = Grandstander({
  subsets: ["latin"],
  variable: "--font-grandstander",
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grandstander.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
